version: "3"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    restart: always
    ports:
      - 8000:8000
    command: uvicorn app.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
